django_basic/conf/urls.py
# from django.contrib import admin
# from django.urls import path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

# urlに対してどんな処理をするか

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path関数の第1引数はurlの指定、第2引数は呼び出すビュー
    # urlの末尾には必ず『/』を入れるように統一する
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')), # myappのurls.pyを読み込む
    path('myapp2/', include('myapp2.urls')) # myappのurls.pyを読み込む
]

django_basic/myapp/urls.py
from django.urls import path
# 『.』は今いる場所（カレントディレクトリ）、
# ここでは from myapp import views でも可能
from . import views

app_name = 'myapp'

# urlpatternsという変数名を書き間違えるとエラー出る
# urls.pyは自分で作るファイル名なのでつづりミスに要注意
urlpatterns = [
    # どのurlでどのビューを呼ぶかを登録する
    # views.pyのhello関数を呼ぶ
    path('hello/', views.hello, name='hello'),
    path('home/', views.home, name='home'),
    path('home2/', views.home2, name='home2'),
    path('kome/', views.kome, name='kome'),
    # クラスビューの時のpathの記述の仕方
    # views.クラス名.as_view() と書く必要がある
    path('home3/', views.Home.as_view(), name='home3'),
    path('lesson/', views.lesson, name='lesson')
]

django_basic/templates/base.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ja">
  <head>
<!--本来は<link rel="stylesheet" href="ファイルのパス">-->
      <link rel="stylesheet" href="{% static 'css/basic.css' %}">
      <title>{% block title %}Python 講座{% endblock %}</title>
  </head>
  <body>
      <p><a href="{% url 'myapp:home' %}">Homeへ</a></p>
      <div id="content">
        {% block content %}{% endblock %}
      </div>
  </body>
  </html>