django_ensyu1/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('article/list/', views.ArticleListView.as_view(), name='article_list'),
    path('tag/list/', views.TagListView.as_view(), name='tag_list'),
    path('category/list/', views.CategoryListView.as_view(), name='category_list'),
    path('article/detail/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('tag/create/', views.TagCreateView.as_view(), name="tag_create"),
    path('article/create/', views.ArticleCreateView.as_view(), name="article_create"),
    path('article/update/<int:pk>/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('comment/create/<int:pk>/', views.CommentCreateView.as_view(), name="comment_create")
]

django_ensyu1/conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

django_ensyu1/blog/models.py
# Create your models here.
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')  # 複数行の入力欄
    # djangoで現在時間を取得するときは『timezone.now』
    # timezone.nowをdefaultにいれると、現在時刻がデフォルトで入力済みになる
    created_at = models.DateTimeField('作成日', default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')

    # タグは複数紐づく。また、タグを設定しないことも可能にしている(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='タグ')

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField('名前', default='名無し', max_length=255)
    text = models.TextField('コメント内容')
    target = models.ForeignKey(
        Article, on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='紐づく記事'
    )

    def __str__(self):
        return self.text[:50]

django_ensyu1/blog/forms.py
from django import forms
from .models import Tag, Article, Comment


class TagCreateForm(forms.ModelForm):
    class Meta:
        model = Tag
        # ページに表示したいモデルのフィールドを、文字列で書きます
        fields = ('name',)


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        # ページに表示したいモデルのフィールドを、文字列で書きます
        fields = ('title', 'text', 'tags', 'category')


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        # ページに表示したいモデルのフィールドを、文字列で書きます
        fields = ('title', 'text', 'tags', 'category')


class SearchForm(forms.Form):
    keyword = forms.CharField(label='キーワード', required=False)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'text')

django_ensyu1/blog/views.py
from django.views.generic import CreateView, DetailView, UpdateView, FormView, ListView

# Create your views here.
from django.views import generic
from django.urls import reverse_lazy
from .models import Article, Tag, Category, Comment
from .forms import TagCreateForm, ArticleCreateForm, ArticleUpdateForm, SearchForm, CommentCreateForm
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect


class Home(generic.TemplateView):
    template_name = 'blog/home.html'


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/article_list.html'

    # 並び替えをする order_by('フィールド名') デフォルトは昇順
    # order_by('-フィールド名') 『-』をつけると降順
    queryset = Article.objects.all().order_by('-created_at')

    # 選択肢となるデータの一覧

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(self.request.GET)
        return context

    def get_queryset(self):
        # 絞り込みのために上書き
        queryset = super().get_queryset()  # .order_by('-created_at') #ここで並び替えを書いてもいい

        # GETパラメータを、フォームに紐づける
        form = SearchForm(self.request.GET)
        form.is_valid()  # フォームからデータを取り出すのに必要な行

        # 値 = フォームオブジェクト.cleaned_data.get('フォームオブジェクトのフィールド名')
        keyword = form.cleaned_data.get('keyword')
        # management_code = form.cleaned_data.get('management_code')
        # price_begin = form.cleaned_data.get('price_begin')
        # price_end = form.cleaned_data.get('price_end')
        # group = form.cleaned_data.get('group')

        if keyword:
            # .filter(モデルオブジェクトのフィールド名=値)
            # queryset = queryset.filter(title__icontains=keyword)
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )

        # if management_code:
        #     queryset = queryset.filter(management_code=management_code)
        # if group:
        #     queryset = queryset.filter(group=group)
        # if price_begin:
        #     # filter(フィールド名__特殊条件=値)
        #     # gte greater than equal >=のこと
        #     queryset = queryset.filter(price__gte=price_begin)
        # if price_end:
        #     queryset = queryset.filter(price__lte=price_end)
        return queryset


class TagListView(ListView):
    model = Tag
    template_name = 'blog/tag_list.html'


class CategoryListView(ListView):
    model = Category
    template_name = 'blog/category_list.html'


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'

    # DetailViewがもともと持っている、get_objectメソッドの紹介。
    # データベースから、1つのデータを取得する

    def get_object(self, queryset=None):
        # self.kwargsは、URL内の int:pkといった部分が入っている
        article = Article.objects.get(pk=self.kwargs['pk'])
        # →Staff.objects.get(pk=1)  # 今回、URLは/staff_detail/1/
        # →Staff.objects.get(id=1)  # pkというのは、primarykeyのこと。今回ならidフィールドのこと
        # print(staff.name) # ここで書くとターミナルに表示される
        return article

    def get_context_data(self, **kwargs):
        # contextは取ってこなければならない
        # 新しく作るとstaffに入ったデータが取ってこられない
        context = super().get_context_data(**kwargs)
        # DetailViewにはget_objectメソッドがあり
        # URLのidを元にモデルのインスタンスを取得している
        article = self.get_object()
        tags = article.tags.all()
        context['books'] = tags
        return context


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = 'blog/tag_create.html'
    success_url = reverse_lazy('blog:article_list')  # テンプレートで使った、urlタグみたいなもの
    form_class = TagCreateForm


class ArticleCreateView(generic.CreateView):
    model = Article
    template_name = 'blog/article_create.html'
    success_url = reverse_lazy('blog:article_list')  # テンプレートで使った、urlタグみたいなもの
    form_class = ArticleCreateForm


class ArticleUpdateView(generic.UpdateView):
    model = Article
    template_name = 'blog/article_update.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = ArticleUpdateForm


class ArticleDeleteView(generic.DeleteView):
    model = Article
    template_name = 'blog/article_delete.html'
    success_url = reverse_lazy('blog:article_list')


class CommentCreateView(generic.CreateView):
    model = Comment
    template_name = 'blog/comment_create.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = CommentCreateForm

    def form_valid(self, form):
        # form.save(commit=False) データベースにはまだ保存しない
        # commit=False　ビューでモデルのフィールドを埋めるために使う引数
        comment = form.save(commit=False)

        # commentモデルのtargetフィールドをここで埋める
        # モデル名.objects.get(フィールド=値) 1つだけDBから取り出すのに使うメソッドがget
        # url内の<int:pk>はself.kwargs['pk']で取得できる
        comment.target = Article.objects.get(pk=self.kwargs['pk'])

        # 上2行をまとめてこう書かれている場合も多い
        # form.instance.target = Article.objects.get(pk=self.kwargs['pk'])

        comment.save()
        return redirect('blog:article_list')

django_ensyu1/templates/base.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ja">
  <head>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>{% block title %}django_ensuy1{% endblock %}</title>
  </head>
  <body>
    <ul id="nav">
      <li><a href="{% url 'blog:home' %}">Homeへ</a></li>
      <li><a href="{% url 'blog:article_list' %}">記事一覧へ</a></li>
      <li><a href="{% url 'blog:article_create' %}">記事作成へ</a></li>
      <li><a href="{% url 'blog:tag_create' %}">タグ作成へ</a></li>
    </ul>
<!--    <p>base.htmlを使っています！</p>-->
      <div id="content">
        {% block content %} {% endblock %}
      </div>
  </body>
  </html>

django_ensyu1/templates/blog/article_create.html
{% extends 'base.html' %}

{% block content %}
<h1>記事作成</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>
{% endblock %}

django_ensyu1/templates/blog/article_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>"{{ object }}"を削除してもよろしいですか?</p>
    <div><input type="submit" value="削除">
    /<a href="{% url 'blog:article_list' %}">一覧へ戻る</a></div>
</form>

{% endblock %}

django_ensyu1/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>記事詳細
        / <a href="{% url 'blog:article_update' article.pk %}">更新</a>
        / <a href="{% url 'blog:article_delete' article.pk %}">削除</a>
    </h1>

    <h3>タイトル</h3>
        <p>{{article.title}}</p>

    <h3>カテゴリ</h3>
        <p>{{article.category}}</p>

    <h3>タグ</h3>
        <p>
         <!-- インスタンス.ManyToManyField名.all -->
            {% for tag in article.tags.all %}
                {{ tag.name }},
            {% endfor %}
        </p>

    <h3>作成日</h3>
        <p>{{article.created_at | date:'Y/m/d H:i:s'}}</p>

    <h3>本文</h3>
        <!--linebreaks: 改行をHTML上に反映させるフィルタ-->
        <p>{{article.text | linebreaks }}</p>

    <h1>コメント欄
        / <a href="{% url 'blog:comment_create' article.pk %}">コメント投稿</a>
    </h1>
    {% for comment in article.comment_set.all %}

        <div>
            <h4>{{ comment.name }}</h4>
            <p>{{ comment.text | linebreaks }}</p>
        </div>
        <hr>
    {% endfor %}

{% endblock %}

django_ensyu1/templates/blog/article_list.html
{% extends 'base.html' %}

{% block content %}

  <h1>記事一覧</h1>

<form action="" method="GET">
    {{ form.as_div }}
    <button type="submit">検索</button>
</form>

<!--  モデル名小文字表記_list に、そのモデルのデータ一覧が入って渡ってくる-->

  <p>{% for article in article_list %}
    <!-- モデルのインスタンスが渡されている 変数名.フィールド -->
      <a href="{% url 'blog:article_detail' article.pk %}">{{article.title}}</a>:
      {% for tag in article.tags.all %}
        {{ tag.name }}
      {% endfor %}
  <br>
  {% endfor %}
  </p>

{% endblock %}

django_ensyu1/templates/blog/article_update.html
{% extends 'base.html' %}

{% block content %}
<h1>記事更新</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">更新</button>
</form>
<a href="{% url 'blog:article_list' %}">一覧へ戻る</a>
{% endblock %}

django_ensyu1/templates/blog/category_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>カテゴリー一覧</h1>
        <div>
          {% for category in category_list %}
          {{ category.name }}
          {% endfor %}
        </div>

{% endblock %}

django_ensyu1/templates/blog/comment_create.html
{% extends 'base.html' %}

{% block content %}
<h1>コメント投稿</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>
{% endblock %}

django_ensyu1/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Homeです！</h1>

{% endblock %}

django_ensyu1/templates/blog/tag_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}

django_ensyu1/templates/blog/tag_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>タグ一覧</h1>

    {% for tag in tag_list %}
        <p>{{ tag.name }}</p>
    {% endfor %}


{% endblock %}