django_advance/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 追加
from django.conf.urls.static import static  # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),# accountsのurls.pyを読み込む
    path('crud/', include('crud.urls'))
]

# DEBUGがTrueの時だけ
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_advance/search/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'search'
urlpatterns = [
    path('', login_required(views.CustomGoodsListView.as_view()), name='custom_goods_list'),
    path('group_create/', login_required(views.GroupCreateView.as_view()), name='group_create'),
    path('custom_goods_create/', login_required(views.CustomGoodsCreateView.as_view()), name='custom_goods_create'),
]

django_advance/search/models.py
from django.db import models
from django.core.validators import MaxValueValidator


class GoodsGroup(models.Model):
    name = models.CharField('商品グループ', unique=True, max_length=10, null=True)

    def __str__(self):
        return self.name


class CustomGoods(models.Model):
    name = models.CharField('商品名', unique=True, max_length=100, null=True)
    management_code = models.CharField('管理コード', unique=True, max_length=20)
    price = models.IntegerField('価格', validators=[MaxValueValidator(1000000000)])
    release_date = models.DateField('発売日', blank=True, null=True)
    release_flag = models.BooleanField('発売済み', default=False)
    description = models.CharField('説明', max_length=100000)
    image = models.ImageField('画像', null=True, blank=True, upload_to='goods_images/')
    state_flag = models.BooleanField('運用状況', default=True)
    group = models.ForeignKey(GoodsGroup, on_delete=models.CASCADE, verbose_name='商品グループ')

    def __str__(self):
        return self.name

django_advance/search/forms.py
from django import forms
from .models import GoodsGroup, CustomGoods


class GroupCreationForm(forms.ModelForm):
    class Meta:
        model = GoodsGroup
        fields = ("name",)  # 1要素なのでカンマをつける


class CustomGoodsCreationForm(forms.ModelForm):
    class Meta:
        model = CustomGoods
        fields = ('name', 'management_code', 'price', 'release_date', 'release_flag', 'description', 'image', 'group')


# モデルの内容を元にデータを作成する際だけModelFormを使う、それ以外はForm
class CustomGoodsSearchForm(forms.Form):
    group = forms.ModelChoiceField(queryset=GoodsGroup.objects, label='グループ', required=False, empty_label='選択してください')
    name = forms.CharField(label='商品名', required=False)
    management_code = forms.CharField(label='管理コード', required=False)
    price_begin = forms.IntegerField(label='価格下限', required=False)
    price_end = forms.IntegerField(label='価格上限', required=False)

django_advance/search/views.py
from django.views import generic
from .models import GoodsGroup, CustomGoods
from .forms import GroupCreationForm, CustomGoodsCreationForm, CustomGoodsSearchForm


class GroupCreateView(generic.CreateView):
    model = GoodsGroup
    success_url = '/search/group_create'
    template_name = 'search/group_create.html'
    form_class = GroupCreationForm


class CustomGoodsCreateView(generic.CreateView):
    model = CustomGoods
    success_url = '/search/custom_goods_create'
    template_name = 'search/custom_goods_create.html'
    form_class = CustomGoodsCreationForm


class CustomGoodsListView(generic.ListView):
    model = CustomGoods
    template_name = 'search/custom_goods_list.html'
    paginate_by = 1  # ページングに使う変数。1件ずつ表示
    # 並び替えをする order_by('フィールド名') デフォルトは昇順
    # order_by('-フィールド名') 『-』をつけると降順
    queryset = CustomGoods.objects.all().order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CustomGoodsSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        # 絞り込みのために上書き
        queryset = super().get_queryset()

        # GETパラメータを、フォームに紐づける
        form = CustomGoodsSearchForm(self.request.GET)
        form.is_valid()  # フォームからデータを取り出すのに必要な行

        # 値 = フォームオブジェクト.cleaned_data.get('フィールド名')
        name = form.cleaned_data.get('name')
        management_code = form.cleaned_data.get('management_code')
        price_begin = form.cleaned_data.get('price_begin')
        price_end = form.cleaned_data.get('price_end')
        group = form.cleaned_data.get('group')

        if name:
            # .filter(フィールド名=値)
            queryset = queryset.filter(name=name)
        if management_code:
            queryset = queryset.filter(management_code=management_code)
        if group:
            queryset = queryset.filter(group=group)
        if price_begin:
            # filter(フィールド名__特殊条件=値)
            # gte greater than equal >=のこと
            queryset = queryset.filter(price__gte=price_begin)
        if price_end:
            queryset = queryset.filter(price__lte=price_end)
        return queryset

django_advance/templates/search/custom_goods_create.html
{% extends 'base.html' %}

{% block content %}
<h2>商品作成ページ</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" id="save" value="作成">
</form>
{% endblock %}

django_advance/templates/search/custom_goods_list.html
{% extends 'base.html' %}
{% load search %}
{% block content %}
<h2>商品グループ一覧・検索ページ</h2>
<form action="" method="GET">
    {{ form.as_div }}
    <button type="submit">検索</button>
</form>
{% for goods in customgoods_list %}
    <div>
        {{ goods.name }}
    </div>
{% endfor %}

<!-- 前ページのリンク作成 -->
{% if page_obj.has_previous %}
    <a href="?{%  url_replace request 'page' page_obj.previous_page_number %}">前のページへ</a>
{% endif %}

<!-- 1 2 3 4 5といった部分のリンク作成 -->
{% for link_page in page_obj.paginator.page_range %}
    {% if link_page == page_obj.number %}
        <span>{{ link_page }}</span>
    {% else %}
       <a href="?{%  url_replace request 'page' link_page %}">{{ link_page }}</a>
    {% endif %}
{% endfor %}

<!-- 次のページ のリンク作成 -->
{% if page_obj.has_next %}
    <a href="?{%  url_replace request 'page' page_obj.next_page_number %}">次のページへ</a>
{% endif %}

{% endblock %}

django_advance/templates/search/group_create.html
{% extends 'base.html' %}

{% block content %}
<h2>商品グループ作成ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" id="save" value="作成">
</form>

{% endblock %}