contact_form/conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('contacts.urls'))
]

contact_form/contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'
urlpatterns = [
    path('corporate_input/', CorporateContactInput.as_view(), name='corporate_input'),
    path('corporate_confirm/', CorporateContactConfirm.as_view(), name='corporate_confirm'),
    path('corporate_create/', CorporateContactCreate.as_view(), name='corporate_create'),
    path('corporate_input/', CorporateContactInput.as_view(), name='corporate_input'),
    path('corporate_confirm/', CorporateContactConfirm.as_view(), name='corporate_confirm'),
    path('corporate_create/', CorporateContactCreate.as_view(), name='corporate_create'),
    path('form_send_complete/', FormSendComplete.as_view(), name='form_send_complete'),
]

contact_form/contacts/models.py
from django.db import models
from django.template.loader import get_template
from accounts.models import CustomUser


def contact_type_handler(contact_type):
    if not isinstance(contact_type, str):
        raise TypeError("contact_type must be str type")

    if contact_type not in ('individual', 'corporate'):
        raise ValueError("contact_type must be 'individual' or 'corporate'")


class BaseContact(models.Model):
    """
    抽象モデル 継承して使うためのモデル
    共通するフィールドやメソッドをまとめた
    """
    datetime = models.DateTimeField(verbose_name='お問合せ日時', auto_now_add=True)
    content = models.TextField(verbose_name='お問合せ内容', blank=False)
    email = models.EmailField(verbose_name='メールアドレス', blank=False)

    class Meta:
        # これがあるとテーブルが作られない
        abstract = True

    def __str__(self):
        return self.content

    @staticmethod
    def base_email_users(form, from_email, contact_type):
        contact_type_handler(contact_type)
        context = {
            'form': form,
        }
        subject_template = get_template('contacts/email/{}_subject.txt'.format(contact_type))
        subject = subject_template.render(context)

        message_template = get_template('contacts/email/{}_message.txt'.format(contact_type))
        message = message_template.render(context)

        CustomUser.email_users(CustomUser.get_users_emailed(), subject, message, from_email)


class IndividualContact(BaseContact):
    """個人からのお問合せ"""
    fullname = models.CharField(verbose_name='氏名', blank=False, max_length=30)
    kana = models.CharField(verbose_name='フリガナ', blank=False, max_length=60)

    @staticmethod
    def email_users(form, from_email):
        BaseContact.base_email_users(form, from_email, 'individual')


class CorporateContact(BaseContact):
    """企業からのお問合せ"""
    corporate_name = models.CharField(verbose_name='企業名', blank=False, max_length=30)
    pic_name = models.CharField(verbose_name='担当者名', blank=False, max_length=30)
    phonenumber = models.CharField(verbose_name='電話番号', blank=False, max_length=16)

    @staticmethod
    def email_users(form, from_email):
        BaseContact.base_email_users(form, from_email, 'corporate')

contact_form/contacts/forms.py
from django import forms
from .models import CorporateContact, IndividualContact
from django.views import generic


class CorporateContactForm(forms.ModelForm):
    class Meta:
        model = CorporateContact
        # '__all__' とすると、全ての入力欄になります
        fields = '__all__'


class IndividualContactForm(forms.ModelForm):
    class Meta:
        model = IndividualContact
        # '__all__' とすると、全ての入力欄になります
        fields = '__all__'

contact_form/contacts/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import CorporateContactForm, IndividualContactForm
from .models import CorporateContact, IndividualContact

from django.template.loader import get_template
from accounts.models import CustomUser
from django.shortcuts import redirect, render


# 確認画面を作る時
# 1. FormViewで、入力欄のあるページを作る CorporateContactInput
# 2. FormViewで、入力内容を表示する確認ページを作る CorporateContactConfirm
# 3. CreateViewで、入力内容を保存するビューを作る CorporateContactCreate

# CreateViewから、データの保存処理をなくしたビューがFormView
class CorporateContactInput(generic.FormView):
    """確認画面機能の、最初の入力ページ"""
    form_class = CorporateContactForm
    template_name = 'contacts/corporate_contact_input.html'

    def form_valid(self, form):
        # 確認画面、戻るボタンを押したときに呼ばれる
        context = {
            'form': form,  # input type="hidden" で隠れていたデータが、ちゃんとはいってます
        }
        return render(
            self.request,
            'contacts/corporate_contact_input.html',
            context
        )


class IndividualContactInput(generic.FormView):
    """確認画面機能の、最初の入力ページ"""
    form_class = IndividualContactForm
    template_name = 'contacts/individual_contact_input.html'

    def form_valid(self, form):
        # 確認画面、戻るボタンを押したときに呼ばれる
        context = {
            'form': form,  # input type="hidden" で隠れていたデータが、ちゃんとはいってます
        }
        return render(
            self.request,
            'contacts/individual_contact_input.html',
            context
        )


class CorporateContactConfirm(generic.FormView):
    form_class = CorporateContactForm

    def form_valid(self, form):
        # 入力ページ (/) で、送信を押すと呼ばれる
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/corporate_contact_confirm.html',
            context
        )

    def form_invalid(self, form):
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/corporate_contact_confirm.html',
            context
        )


class IndividualContactConfirm(generic.FormView):
    form_class = IndividualContactForm

    def form_valid(self, form):
        # 入力ページ (/) で、送信を押すと呼ばれる
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/individual_contact_confirm.html',
            context
        )

    def form_invalid(self, form):
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/individual_contact_confirm.html',
            context
        )


class CorporateContactCreate(generic.CreateView):
    model = CorporateContact
    form_class = CorporateContactForm
    success_url = reverse_lazy('contacts:form_send_complete')

    def form_invalid(self, form):
        # 確認画面で、送信ボタンを押したが、入力内容が悪かった
        # 本来呼ばれないはず
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/corporate_contact_input.html',
            context
        )

    def form_valid(self, form):
        # 確認画面で、送信を押すと呼ばれる

        # モデルフォームのsaveメソッドで、DBに保存される
        # saveメソッドは、モデルインスタンスを返す
        corporate = form.save()

        # テンプレートファイルに、辞書を渡して、メール本文の文字列を作成している
        subject = '題名'
        mail_text_template = get_template('contacts/email/corporate_message.txt')
        context = {
            'corporate': corporate,
        }
        # mail_textには、メールの本文が文字列で作られた状態
        mail_text = mail_text_template.render(context)

        # メールの送信処理
        # モデル名.objects.filter(フィールド名=値)で、絞り込むことができます
        for user in CustomUser.objects.filter(is_received_email=True):
            # 実際にメールを送る。Userモデルに定義されている、メール送信用のメソッド
            user.email_user(subject, mail_text, 'info@a.com')

        return redirect('contacts:form_send_complete')


class IndividualContactCreate(generic.CreateView):
    model = IndividualContact
    form_class = IndividualContactForm
    success_url = reverse_lazy('contacts:form_send_complete')

    def form_invalid(self, form):
        # 確認画面で、送信ボタンを押したが、入力内容が悪かった
        # 本来呼ばれないはず
        context = {
            'form': form
        }
        return render(
            self.request,
            'contacts/individual_contact_input.html',
            context
        )

    def form_valid(self, form):
        # 確認画面で、送信を押すと呼ばれる

        # モデルフォームのsaveメソッドで、DBに保存される
        # saveメソッドは、モデルインスタンスを返す
        individual = form.save()

        # テンプレートファイルに、辞書を渡して、メール本文の文字列を作成している
        subject = '題名'
        mail_text_template = get_template('contacts/email/individual_message.txt')
        context = {
            'individual': individual,
        }
        # mail_textには、メールの本文が文字列で作られた状態
        mail_text = mail_text_template.render(context)

        # メールの送信処理
        # モデル名.objects.filter(フィールド名=値)で、絞り込むことができます
        for user in CustomUser.objects.filter(is_received_email=True):
            # 実際にメールを送る。Userモデルに定義されている、メール送信用のメソッド
            user.email_user(subject, mail_text, 'info@a.com')

        return redirect('contacts:form_send_complete')


class FormSendComplete(generic.TemplateView):
    template_name = 'contacts/form_send_complete.html'

contact_form/templates/contacts/corporate_contact_confirm.html
{% extends "base.html" %}
{% block title %}corporate contact form confirm{% endblock %}

{% block content %}
    <!-- 入力内容を表示している -->
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field.value }} <!--入力内容が表示される-->
        </div>
    {% endfor %}

    <!-- 戻るボタン -->
    <form action="{% url 'contacts:corporate_input' %}" method="POST">
        {% for field in form %}
            {{ field.as_hidden }}<!--入力欄を隠している-->
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
    </form>
    <hr>

    <!-- 送信ボタン -->
    <form action="{% url 'contacts:corporate_create' %}" method="POST">
        {% for field in form %}
         {{ field.as_hidden }}
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/corporate_contact_create.html
{% extends 'base.html' %}

{% block title %}企業のお問合せ作成ページ{% endblock %}
{% block content %}

    <form action="" method="POST">
        {{ form.non_field_errors }}
        <!--入力欄の取り出し方
            1.{{ form.as_p }} 一括で取り出す
            2.{{ form.content }} 1つずつ取り出す
            3.入力欄をforテンプレートタグで取り出す（今回使用）-->
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/corporate_contact_input.html
{% extends 'base.html' %}

{% block title %}corporate contact form input{% endblock %}
{% block content %}
    <form action="{% url 'contacts:corporate_confirm' %}" method="POST">
      {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/form_send_complete.html
{% extends 'base.html' %}
{% block content %}
    <p>フォームの送信が完了しました</p>
{% endblock %}

contact_form/templates/contacts/individual_contact_confirm.html
{% extends "base.html" %}
{% block title %}individual contact form confirm{% endblock %}

{% block content %}
    <!-- 入力内容を表示している -->
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field.value }} <!--入力内容が表示される-->
        </div>
    {% endfor %}

    <!-- 戻るボタン -->
    <form action="{% url 'contacts:individual_input' %}" method="POST">
        {% for field in form %}
            {{ field.as_hidden }}<!--入力欄を隠している-->
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
    </form>
    <hr>

    <!-- 送信ボタン -->
    <form action="{% url 'contacts:individual_create' %}" method="POST">
        {% for field in form %}
         {{ field.as_hidden }}
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/individual_contact_create.html
{% extends 'base.html' %}

{% block title %}個人のお問合せ作成ページ{% endblock %}
{% block content %}

    <form action="" method="POST">
        {{ form.non_field_errors }}
        <!--入力欄の取り出し方
            1.{{ form.as_p }} 一括で取り出す
            2.{{ form.content }} 1つずつ取り出す
            3.入力欄をforテンプレートタグで取り出す（今回使用）-->
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

contact_form/templates/contacts/individual_contact_input.html
{% extends 'base.html' %}

{% block title %}individual contact form input{% endblock %}
{% block content %}
    <form action="{% url 'contacts:individual_confirm' %}" method="POST">
      {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}